language: python
os: linux
python:
    - 2.7

before_install:
  - sudo apt-get update -q
  - pip install -U pip

addons:
    apt:
        packages:
            - libhdf5-dev
            - libopenmpi-dev
            - openmpi-bin

install:
    - "pip install -r requirements.txt"
    - "pip install git+https://github.com/zuoshifan/cora.git"
    - "pip install git+https://github.com/zuoshifan/aipy.git@zuo/develop"
    - "pip install git+https://github.com/zuoshifan/caput.git@zuo/develop"
    - "pip install -e .[mpi]"

# script:
    # - "sphinx-build -b html -d _build/doctrees   . _build/html"
    # - "cd ~; nosetests tlpipe"